apiVersion: v1
kind: Pod
metadata:
  name: bootcamp-pvc-example-pod
spec:
  containers:
    - name: bootcamp-pvc-example-container
      image: nginx:stable-alpine
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - name: pod-volume
        mountPath: /mnt/data
      ports:
      - containerPort: 80
      # This is the volume we defined earlier
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 8
        exec:
          command: ["ls", "-l", "/mnt/data"]
  volumes:
    - name: pod-volume
      persistentVolumeClaim:
        claimName: bootcamp-pvc-example