apiVersion: v1
kind: Pod
metadata:
  name: bootcamp-pvc-example-pod
spec:
  containers:
    - name: bootcamp-pvc-example-container
      image: nginx:stable-alpine
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - name: pod-volume
        mountPath: /mnt/data
      ports:
      - containerPort: 80
  volumes:
    - name: pod-volume
      persistentVolumeClaim:
        claimName: bootcamp-pvc-example